### ISSUE TITLE
what are the results?

### ISSUE THREAD

**Issue by serhasberk** [LightersWang/3DUNet-BraTS-PyTorch#3]
Hello  Sir Haoran Wang

could you share your results ?

**Comment by LightersWang** [comment]
Sorry for the late reply. 
This repo is just a part of my other project, so I didn't do much of the experiments on the baseline U-Net.

**Comment by serhasberk** [comment]
Thanks for your response

**Comment by serhasberk** [comment]
Could you share the related project with this one?
